### ISSUE TITLE
live tv audio sometimes scrambled 7.1 PCM output to AVR

### ISSUE THREAD

**Issue by bylderup** [CoreELEC/CoreELEC#30] opened 2018-04-23 11:00 UTC
I use a Meccol KI pro and a Pioneer VSX 924 AVR.
Audio Configuration is
ALSA;AML-M8AUDIO HDMI
7.1 Channels
optimised
Default Volume while downmixing
Stereo upmix
no passtrough enabled
AVR shows 7.1 PCM
Sound is still sometimes scrambled like a bad tuned fm station using live tv e.g. ONE HD
Stopping live tv starting a different channel solves the problem. 
direct zapping between channels with different audio features should be avoided else it will happen more often.  
Changing HDMI cable and device did not solve the problem. 
Edit (tested again) : Different KI pro with 8.2.3.1 has not this issue.

part of kodi.log 
12:27:34.495 T:4098785296  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Alle Kanäle/pvr.hts_88548475.pvr
12:27:34.498 T:2917131136  NOTICE: Creating InputStream
12:27:34.502 T:2917131136  NOTICE: Creating Demuxer
12:27:34.751 T:2917131136  NOTICE: Opening stream: 1 source: 256
12:27:34.764 T:2917131136 WARNING: OpenStream - Unsupported stream 1. Stream disabled.
12:27:34.764 T:2917131136  NOTICE: Opening stream: 5 source: 256
12:27:34.764 T:2917131136  NOTICE: Finding audio codec for: 86019
12:27:34.765 T:2917131136  NOTICE: Creating audio thread
12:27:34.765 T:3461337984  NOTICE: running thread: CVideoPlayerAudio::Process()
12:27:34.765 T:2917131136  NOTICE: Opening stream: 6 source: 256
12:27:34.766 T:2917131136  NOTICE: Opening stream: 4 source: 256
12:27:34.766 T:2917131136  NOTICE: waiting for teletext data thread to exit
12:27:34.767 T:2917131136  NOTICE: Creating teletext data thread
12:27:34.767 T:3125797760  NOTICE: running thread: CDVDTeletextData
12:27:34.769 T:2917131136  NOTICE: Opening stream: 1 source: 256
12:27:34.770 T:2917131136  NOTICE: CVideoPlayerVideo::OpenStream - Creating codec: 28
12:27:34.770 T:2917131136  NOTICE: Creating video thread
12:27:34.770 T:3571389312  NOTICE: running thread: video_thread
12:27:34.770 T:2917131136  NOTICE: Opening stream: 5 source: 256
12:27:34.770 T:2917131136  NOTICE: Closing stream player 3
12:27:34.770 T:2917131136  NOTICE: Opening stream: 6 source: 256
12:27:34.771 T:2917131136  NOTICE: Opening stream: 4 source: 256
12:27:34.772 T:2917131136  NOTICE: Opening stream: 1 source: 256
12:27:34.772 T:2917131136  NOTICE: Opening stream: 5 source: 256
12:27:34.772 T:2917131136  NOTICE: Finding audio codec for: 86019
12:27:34.773 T:2917131136  NOTICE: Closing stream player 3
12:27:34.773 T:2917131136  NOTICE: Opening stream: 6 source: 256
12:27:34.773 T:2917131136  NOTICE: Opening stream: 4 source: 256
12:27:34.776 T:3461337984  NOTICE: Creating audio stream (codec id: 86019, channels: 2, sample rate: 48000, no pass-through)
12:27:34.792 T:3571389312  NOTICE: CAMLCodec::OpenDecoder - using V4L2 pts format: 64Bit
12:27:35.219 T:4098785296  NOTICE: Display resolution ADJUST : 1920x1080 @ 50.00i - Full Screen (23) (weight: 0.000)
12:27:38.291 T:4098785296  NOTICE: CVideoPlayer::CloseFile()
12:27:38.291 T:4098785296  NOTICE: VideoPlayer: waiting for threads to exit
12:27:39.132 T:3461337984  NOTICE: CVideoPlayerAudio::Process - stream stalled pts:3.621 clock:3.630
12:27:39.267 T:2917131136  NOTICE: CVideoPlayer::OnExit()
12:27:39.267 T:2917131136  NOTICE: Closing stream player 1
12:27:39.267 T:2917131136  NOTICE: Waiting for audio thread to exit
12:27:39.268 T:3461337984   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
12:27:39.268 T:3461337984  NOTICE: thread end: CVideoPlayerAudio::OnExit()
12:27:39.269 T:2917131136  NOTICE: Closing audio device
12:27:39.308 T:2917131136  NOTICE: Deleting audio codec
12:27:39.309 T:2917131136  NOTICE: Closing stream player 2
12:27:39.309 T:2917131136  NOTICE: waiting for video thread to exit
12:27:39.310 T:3571389312   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
12:27:39.310 T:3571389312  NOTICE: thread end: video_thread
12:27:39.311 T:2917131136  NOTICE: deleting video codec
12:27:39.351 T:2917131136  NOTICE: Closing stream player 4
12:27:39.352 T:2917131136  NOTICE: waiting for teletext data thread to exit
12:27:39.352 T:3125797760   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true (-1)
12:27:39.352 T:3125797760  NOTICE: thread end: data_thread
12:27:39.358 T:2917131136  NOTICE: Closing stream player 3
12:27:39.366 T:4098785296  NOTICE: VideoPlayer: finished waiting
12:27:39.366 T:4098785296  NOTICE: CVideoPlayer::CloseFile()
12:27:39.366 T:4098785296  NOTICE: VideoPlayer: waiting for threads to exit
12:27:39.366 T:4098785296  NOTICE: VideoPlayer: finished waiting

**Comment by afl1** [comment] 2018-04-23 19:12
Partial log without component specific debugging (audio, video,a/v timing) are useless.

**Comment by bylderup** [comment] 2018-04-23 19:50
ok. I didn´t know that.  Have already installed different skin, a lot of audio/video addons and things like Artist slideshow. So I will do a fresh install on a different SD Card without any addional addons, enable debugging and reprodure the issue. Then I´ll send the complete log.zip

**Comment by bylderup** [comment] 2018-04-23 20:37
[kodilog.zip](https://github.com/CoreELEC/CoreELEC/files/1939928/kodilog.zip)
[log-2018-04-23-20.22.55.zip](https://github.com/CoreELEC/CoreELEC/files/1939929/log-2018-04-23-20.22.55.zip)

I hope the upload worked und you can find the issue

**Comment by afl1** [comment] 2018-04-25 13:07
Switch-off stereo upmix and left this job for av receiver. Receiver has better DSP like cheep chinese box.

**Comment by bylderup** [comment] 2018-04-25 14:02
Thats correct.  But stereo upmix is a familiy friendly config. No need for wife, grandma or children to change something with AVR remote.  Issue happens on wetek play2 also.  Cannot reproduce it with older images like 8.2.3.1
I´m not a developer but for me its a software and not a hardware issue.

**Comment by adamg88** [comment] 2018-04-25 18:05
@afl1 should we remove this option the same as sync playback to display?

**Comment by adamg88** [comment] 2018-04-25 18:06
@bylderup kszaq 8.2.3.1 use same kernel so it is unlikely software issue unless problem exists in Kodi and therefore it becomes a Kodi issue and not CoreELEC issue

**Comment by bylderup** [comment] 2018-04-25 18:44
I tested with several images with 2 different AVR, new HDMI cables and 2 different devices.
In 8.2.3.1 it was possible to reproduce it only after a lot of tries and "hardcore" zapping with live tv channels. In an older afl1 8.0.2 image I could reproduce it, also. With rb24 leia on wetek only with direct zapping, but never if tv channel was stopped before chosing a different one. In CoreELEC as described above.  
My thought was, that this is "only" a kind of timing/initialising problem mostly with the rear channels in the audio stream watching live tv.

**Comment by adamg88** [comment] 2018-04-25 19:33
Do you have pass through and ac3 transcode options selected?

**Comment by bylderup** [comment] 2018-04-25 19:49
No. Otherwise I only would have 2 channel mpeg stereo, 2 channel dolby or 5.1 channel ac3 with live tv.
7.1 channel PCM and stereo upmix is best for me. Multichannel sound from all loudspeakers without changing AVR setup...

**Comment by adamg88** [comment] 2018-04-25 19:53
How Stereo Upmix works will depend on the connection type and the number of PCM channels it supports. If the connection type is HDMI and is going to an AVR then PCM 5.1 will generally be supported thus Stereo Upmix will do a PCM 2.0 -> PCM 5.1 upmix, however if connection type is SPDIF then only PCM 2.0 is supported therefore both the Passthrough and the AC3 Transcode options need to be selected for a PCM 2.0 -> AC3 5.1 upmix to be done.

**Comment by afl1** [comment] 2018-04-25 20:14
Upmixing is done in ffmpeg. I can hardly change in ffmpeg upmixing plugin.

**Comment by bylderup** [comment] 2018-04-25 20:38
Compared CoreELEC with afl1 LibreELEC-S905.arm-8.0-8.0.2c-I.img.
live tv channels with dolby 2.0 audio 
7.1 channel HDMI (no passthrough) and upmixing enabled in kodi system/audio 
afl1 image : no problems
CoreELEC image: after channel switching often no decoding but digital noise
Switching to a channel with 5.1 after issue happened doesn´t help
Stopping live tv, selecting a different channel, starting : sound ok...

I´m sorry but something must be different..
For now, I will use passthrough and no stereo upmix in CoreELEC to avoid problems.

**Comment by afl1** [comment] 2018-04-25 21:45
There are different ffmpeg versions 3.1 vs 3.4.

**Comment by adamg88** [comment] 2018-04-26 02:09
The problem is within Kodi/ffmpeg and not CE, why you wouldn't want to use Prologic in your AV unit is absurd and beyond me as it will do a far far better job than what ffmpeg will.

I posted an explanation of how stereo up-mixing should and does work in my previous post, the only downfall is that DD2.0 is not upmixed as you have already experienced and this is sent as-is to the AV unit in which case you would need to turn on that non family friendly option anyway you have been dodging.

**Comment by bylderup** [comment] 2018-05-01 08:43
I don´t know if you are in contact with OSMC devs. Vero 4 K had problems with Multichannel PCM output - comparible to what I have described.  They have fixes in the April update : Fix an issue where noises could be heard on rear channels when playing multichannel PCM on Vero 4K
Maybe its worth to have a look at it.

**Comment by adamg88** [comment] 2018-05-14 20:01
I believe this issue is resolved with the upcoming kernel and setting default audio configuration to fixed.

**Closed by adamg88** 2018-05-14 20:01 UTC
